import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import getEmployee from '@/service/employee/get-employee'
import { ApiContext } from '@/types'

// export async function getServerSideProps() {
//   const url =
//     process.env.NODE_ENV === 'production'
//       ? `https://${process.env.NEXT_PUBLIC_BACKEND_SERVER}:${process.env.NEXT_PUBLIC_PORT}`
//       : `http://localhost:8090`
//   const { status } = await fetch(url + '/status').then((x) => x.json())
//   const { username } = await fetch(url + '/username').then((x) => x.json())
//   return {
//     props: {
//       status: status,
//       username: username,
//     },
//   }
// }

// type Props = {
//   status: string
//   username: string
// }

type HomePageProps = InferGetStaticPropsType<typeof getStaticProps>

const HomePage: NextPage<HomePageProps> = ({ employee }: HomePageProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        <div>employee is: {employee.Name.FirstName}.</div>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const context: ApiContext = {
    apiRootUrl: process.env.API_BASE_URL || 'http://localhost:8090',
  }
  const employee = await getEmployee(context, { id: 1 })
  return {
    props: {
      employee,
    },
  }
}

export default HomePage
