import Head from 'next/head'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const url = process.env.NODE_ENV === 'production' 
    ? `https://${process.env.NEXT_PUBLIC_BACKEND_SERVER}:${process.env.NEXT_PUBLIC_PORT}`
    : `http://localhost:8090`;
  const {status} = await fetch(url + "/status").then(x => x.json());
  const {username} = await fetch(url + "/username").then(x => x.json());
  return {
    props: {
      status: status,
      username: username,
    }
  }
}

type Props = {
  status: string;
  username: string;
}
export default function Home({status, username}: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>Status is: {status}. your name is: {username}</div>
      </main>
    </div>
  )
}
